# Generated by Django 5.2.5 on 2025-09-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_listing_metadata_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kyc_doc',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sumsub_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sumsub_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sumsub_verification_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
