# Generated by Django 5.2.5 on 2025-09-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_profile_kyc_doc_profile_sumsub_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
