# Generated by Django 5.2.5 on 2025-09-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_profile_kyc_rejection_reason_profile_kyc_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('auto_approved', 'Auto Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='not_submitted', max_length=20),
        ),
    ]
