# Generated by Django 5.2.5 on 2025-09-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_profile_kyc_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='metadata_cid',
            new_name='ipfs_metadata_cid',
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='contract_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(default='US', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='recommendation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='token_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='validation_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='valuation_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='valuation_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='valuation_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('apartment', 'Apartment'), ('commercial', 'Commercial'), ('land', 'Land'), ('industrial', 'Industrial')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_validation', 'Pending Validation'), ('available', 'Available'), ('sold', 'Sold'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
